version: "3.2"

services:
    server:
        volumes:
            - ./geoip:/geoip
    worker:
        volumes:
            - ./geoip:/geoip
    geoipupdate:
        image: "maxmindinc/geoipupdate:latest"
        restart: unless-stopped
        volumes:
            - "./geoip:/usr/share/GeoIP"
        environment:
            GEOIPUPDATE_EDITION_IDS: "GeoLite2-City GeoLite2-ASN"
            GEOIPUPDATE_FREQUENCY: "8"
            GEOIPUPDATE_ACCOUNT_ID: "YOUR_MAXMIND_ID"
            GEOIPUPDATE_LICENSE_KEY: "YOUR_MAXMIND_KEY"
volumes:
    geoip:
        driver: local