services:

#    ipv6nat-mailcow:
#      image: bash:latest
#      restart: "no"
#      entrypoint: ["echo", "ipv6nat disabled in compose.override.yml"]

##### Prometheus Exporter
##### Github repository: https://github.com/mailcow/prometheus-exporter
##### 


    prometheus:
      image: ghcr.io/mailcow/prometheus-exporter:2
      command: '--api-key=YOUR-MAILCOW-API-KEY'
      restart: unless-stopped
      environment:
        - MAILCOW_EXPORTER_HOST=mail.YOUR.DOMAIN
        - MAILCOW_EXPORTER_API=YOUR-MAILCOW-API-KEY
        - MAILCOW_EXPORTER_SECURITY_TOKEN=MAILCOW-SECURITY-TOKEN
        - PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
      labels:
        org.opencontainers.image.created: "2025-03-12T14:11:18.877Z"
        org.opencontainers.image.description: "Mailcow Prometheus"
        org.opencontainers.image.licenses: "MIT"
        org.opencontainers.image.revision: "85d38b3b1c1c18212d963e9acee0a327f485d07f"
        org.opencontainers.image.source: "https://github.com/mailcow/prometheus-exporter"
        org.opencontainers.image.title: "prometheus-exporter"
        org.opencontainers.image.url: "https://github.com/mailcow/prometheus-exporter"
        org.opencontainers.image.version: "2.0.1"
      ports:
        - "9099:9099"
      networks:
        mailcow-network:
          aliases:
            - metrics